packages:
  - 'packages/*'
  - '!packages/tests/smoke/**'
  - '!packages/tests/module/**'
pnpm:
  strictDepBuilds: true
  minimumReleaseAgeExclude:
    - '@gingacodemonkey/config'
  trustPolicyIgnoreAfter: 43200
  trustPolicy: no-downgrade
  blockExoticSubdeps: true
  minimumReleaseAge: 4320
